### ISSUE TITLE
If at top of page, scroll up does not hide pointer anymore

### ISSUE THREAD

**Issue by ncasdpo** [KennethSundqvist/hide-mouse-pointer-browser-extension#4]
If at top of page, scroll up does not hide pointer anymore.

I'm fairly sure it used to, as my main use of this extension was scrolling up on YouTube when watching a video (a situation where you are at the top of the page), but when scrolling up now, the pointer is not hidden.

This behaviour isn't just seen on YouTube, it is happening on every site

**Comment by KennethSundqvist** [comment]
Thank you for reporting this bug.

I have released a fix for this in version 2.0.1.

**Comment by ncasdpo** [comment]
Nice one, am seeing it's fixed in my browser as well. Do you have a Buy Me a Coffee or equivalent @KennethSundqvist?
